--2014-12-11 - Create users

CREATE USER 'lbc_master'@'%' IDENTIFIED BY '***';

GRANT ALL PRIVILEGES ON * . * TO 'lbc_master'@'%' IDENTIFIED BY '***' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
